import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — Bottlecap",
  description: "Terms and conditions for using Bottlecap.",
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-4xl font-bold text-[#1A1A1A] mb-8">
        Terms of Service
      </h1>
      <p className="text-sm text-[#767676] mb-8">
        Last updated: February 2026
      </p>

      <div className="prose prose-neutral max-w-none space-y-8 text-[#1A1A1A]">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Service Description</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            Bottlecap provides AI-powered manufacturing feasibility analysis
            reports. Our reports are generated using artificial intelligence and
            should be treated as informational guidance, not professional
            manufacturing or legal advice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Payment &amp; Pricing</h2>
          <ul className="list-disc pl-6 space-y-1 text-[#6B6B6B]">
            <li>Single Report: $99 USD (one-time)</li>
            <li>Monthly Subscription: $199 USD/month</li>
            <li>Supplier List Add-on: $199 USD (one-time)</li>
          </ul>
          <p className="text-[#6B6B6B] leading-relaxed mt-2">
            All payments are processed securely through Stripe. Prices are in US
            dollars and may be subject to applicable taxes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. Refund Policy</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            We offer a full refund within 72 hours of purchase if you are not
            satisfied with your report. To request a refund, email{" "}
            <a
              href="mailto:hello@bottlecap.io"
              className="text-[#FF6B35] hover:underline"
            >
              hello@bottlecap.io
            </a>{" "}
            with your report ID.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. AI-Generated Content</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            Reports are generated by AI (Anthropic&apos;s Claude) and may contain
            estimates, projections, or recommendations based on available data.
            While we strive for accuracy:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-[#6B6B6B]">
            <li>
              Tariff rates, HS codes, and cost estimates are approximations and
              may change.
            </li>
            <li>
              Supplier recommendations are based on AI analysis, not personal
              verification (unless you purchase the verified supplier list).
            </li>
            <li>
              You should independently verify critical information before making
              business decisions.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Intellectual Property</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            You retain all rights to your product ideas and descriptions
            submitted to Bottlecap. Your report is yours to use, share, and
            reference as you see fit. We do not claim ownership of your product
            concepts.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Limitation of Liability</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            Bottlecap is provided &ldquo;as is&rdquo; without warranties of any
            kind. We are not liable for any business decisions made based on our
            reports. Our total liability is limited to the amount you paid for
            the specific report in question.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Changes to Terms</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            We may update these terms from time to time. Continued use of
            Bottlecap after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Contact</h2>
          <p className="text-[#6B6B6B] leading-relaxed">
            For questions about these terms, email us at{" "}
            <a
              href="mailto:hello@bottlecap.io"
              className="text-[#FF6B35] hover:underline"
            >
              hello@bottlecap.io
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  )
}
